apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: alloy
  namespace: argocd

spec:
  project: default

  sources:

    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: "1.11.1"

      helm:
        releaseName: alloy
        valueFiles:
          - $values/values/alloy.yaml

    - repoURL: https://github.com/vvknyazev/pdp-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
